apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-oj0u
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0019-tenant/ci1t-830-0019-app/devfile-sample-oj0u@sha256:09363bd397e218215773c4153171b68ef10c3798e61d5729e151aa1fd3858ab0
        name: my-nodejs
        resources: {}
status: {}
